[package]
name = "underscore_txt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ttf-parser = "^0.15"
underscore_64 = "^0.2.0"
