[package]
name = "_64"
version = "0.1.0"
authors = ["Zeno <zeno@sevencubed.tech>"]
edition = "2018"

[build-dependencies]
bindgen = "0.60"

[features]
minsize = []

[profile.release]
panic = "abort"
lto = true
opt-level = "z"
