[package]
name = "_64"
version = "0.1.0"
authors = ["Zeno <zeno@sevencubed.tech>"]
edition = "2018"

[dependencies]
_sys = {path ="./_sys"}

[features]
minsize = []

[profile.release]
panic = "abort"
lto = true
opt-level = "z"
