[package]
name = "underscore_64"
description = "A minsize focused multimedia library"
version = "0.1.0"
license-file = "LICENSE.md"
authors = ["Zeno <zeno@sevencubed.tech>"]
edition = "2018"

[workspace]

[dependencies]
_sys = { version = "0.1.0", package = "underscore_sys" }

[patch.crates-io]
_sys = { package = "underscore_sys", path = "_sys" }

[features]
minsize = []

[profile.release]
panic = "abort"
lto = true
opt-level = "z"
