[package]
name = "underscore_64"
description = "A minsize graphics library"
version = "0.2.0"
license = "MIT"
authors = ["Zeno <zeno@sevencubed.tech>"]
edition = "2018"

[workspace]
members = ["underscore_sys"]

[dependencies]
_sys = { package = "underscore_sys", version = "0.1.0" }

[patch.crates-io]
_sys = { package = "underscore_sys", path = "underscore_sys" }

[features]
minsize = []

[profile.release]
panic = "abort"
lto = true
opt-level = "z"
