[package]
name = "_64"
description = "A minsize-oriented graphics engine"
version = "0.1.0"
license = "MIT"
authors = ["Zeno <zeno@sevencubed.tech>"]
edition = "2018"

[[bin]]
name = "_64"
path = "src/main.rs"

[workspace]
members = ["underscore_64", "underscore_64/underscore_sys"]

[dependencies]
underscore_64 = "^0.2.0"

[patch.crates-io]
underscore_sys = { path = "./underscore_64/underscore_sys" }
underscore_64 = { path = "./underscore_64" }

[features]
minsize = []

[profile.release]
panic = "abort"
lto = true
opt-level = "z"
