[package]
name = "underscore_64"
description = "A minsize-oriented graphics engine"
version = "0.2.0"
license = "MIT"
authors = ["Zeno <zeno@sevencubed.tech>"]
edition = "2018"

[[bin]]
name = "_64"
path = "src/main.rs"

[workspace]
members = ["underscore_sys", "underscore_sdl", "underscore_gui", "underscore_gfx", "underscore_core"]

[dependencies]
underscore_core = "^0.1.0"
underscore_gfx = "^0.1.0"
underscore_gui = "^0.1.0"
underscore_sdl = "^0.1.0"
underscore_sys = "^0.1.1"
log = { version = "^0.4", optional = true }

[patch.crates-io]
underscore_core = { path = "underscore_core" }
underscore_gfx = { path = "underscore_gfx" }
underscore_gui = { path = "underscore_gui" }
underscore_sdl = { path = "underscore_sdl" }
underscore_sys = { path = "underscore_sys" }

[build-dependencies]
ttf-parser = { version = "^0.15", optional = true }

[features]
edit = ["underscore_core/default_alloc", "underscore_core/default_vec", "log", "ttf-parser"]

[profile.release]
panic = "abort"
lto = true
opt-level = "z"
