[package]
name = "log_64"
description = "4/5 beavers prefer log_64"
version = "0.1.1"
license = "MIT"
authors = ["Zeno <zeno@0x157.tech>"]
edition = "2018"

[dependencies]
log = { version = "^0.4.0", default-features = false }
