[package]
name = "math_64"
description = "Only the numbers 1, 3, 5, 7 or 9 work. It's very odd."
version = "0.1.0"
license = "MIT"
authors = ["Zeno <zeno@0x157.tech>"]
edition = "2018"

[dependencies]
log_64 = "^0.1.0"
mem_64 = "^0.1.0"
