[package]
name = "min_triangle"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
_64 = { package = "underscore_64", path = "../" }

[[bin]]
name = "min_triangle"
path = "main.rs"
