[package]
name = "gui_64"
description = "This crate is all gooey..."
version = "0.1.0"
license = "MIT"
edition = "2021"

[dependencies]
gfx_64 = "^0.1.0"
log_64 = "^0.1.0"
math_64 = "^0.1.0"

ttf-parser = { version = "^0.15", default-features = false }
