[package]
name = "underscore_gui"
version = "0.1.0"
edition = "2021"

[dependencies]
underscore_64 = "^0.2.0"
ttf-parser = "^0.15"
log = "^0.4.0"

[patch.crates-io]
underscore_64 = { path = "../underscore_64" }
