[package]
name = "underscore_gui"
version = "0.1.0"
edition = "2021"

[dependencies]
underscore_core = "^0.1.0"
underscore_gfx = "^0.1.0"
underscore_sys = "^0.1.1"
ttf-parser = { version = "^0.15", default-features = false }
log = { version = "^0.4", default-features = false }
