[package]
name = "underscore_sdl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
underscore_64 = "0.2.0"

[build-dependencies]
bindgen = "0.60"
