[package]
name = "underscore_sys"
description = "openGL and SDL2 bindings for _64"
version = "0.1.0"
license-file = "../LICENSE.md"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
bindgen = "0.60"
