name: Build And Test
on: [pull_request]
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/
            ~/.rustup/
          key: ${{ runner.os }}-nightly-2022-06-20

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2022-06-20
          default: true

  build:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/
            ~/.rustup/
          key: ${{ runner.os }}-nightly-2022-06-20
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/
            target/
          key: ${{ runner.os }}-${{ hashFiles('Cargo.lock') }}

      - run: sudo apt-get install libsdl2-dev
      - run: cargo build --release

  test:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/
            ~/.rustup/
          key: ${{ runner.os }}-nightly-2022-06-20
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/
            target/
          key: ${{ runner.os }}-${{ hashFiles('Cargo.lock') }}

      - run: sudo apt-get install libsdl2-dev
      - run: cargo test --release
