name: Build And Test
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    container: zeno343/underscore_build:latest
    steps:
      - uses: actions/checkout@v3
      - run: ls $CARGO_HOME/bin && cargo build --release
        env:
          CARGO_HOME: /usr/local/cargo
