name: Build And Test
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    container: zeno343/underscore_build:latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        name: Cache Crates
        id: cache-crates
        with:
          path: ${{ container.env.CARGO_HOME }}
          key: ${{ cargo.env.NIGTHLY }}-${{  cargo.env.TARGET }}-${{ hashFiles('**/Cargo.lock') }}      
      - run: cargo fetch
