name: Build And Test
on: [pull_request]
jobs:
  build:
    id: build
    runs-on: ubuntu-latest
    container: zeno343/underscore_build:latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        name: Cache Crates
        id: cache-crates
        with:
          path: $CARGO_HOME
          key: $NIGTHLY-$TARGET-${{ hashFiles('**/Cargo.lock') }}      
      - run: cargo fetch
