name: Build And Test
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    container: zeno343/underscore_build:latest
    steps:
      - run: echo "CARGO_HOME=$CARGO_HOME >> $GITHUB_ENV"
             echo "TARGET=$TARGET >> $GITHUB_ENV"
             echo "NIGHTLY=$NIGHTLY >> $GITHUB_ENV"
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        name: Cache Crates
        id: cache-crates
        with:
          path: $CARGO_HOME
          key: ${{ env.NIGHTLY }}-${{ env.TARGET }}-${{ hashFiles('**/Cargo.lock') }}      
      - run: cargo fetch
